### ISSUE TITLE
移动端boder显示不全的问题

### ISSUE THREAD

**Issue by ibreathebsb** [ibreathebsb/notes#1]
border右侧看起来好像被截断了

```html 
<div class="img-container">
    <img src="test.jpg"  alt="">
</div>
```

```css 
.img-container {
    width: 75px;
    height: 75px;
    border: 2px solid #FFDD52;
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
}
```

最后定位到原因是 `translate`引起的，解决方法
` transform: translate(-50%, -50%) translateZ(0);`
